function aa222_apply_simulink_physics_update(modelName)
%AA222_APPLY_SIMULINK_PHYSICS_UPDATE Rebuild the active aero path in Simulink.
%   This patches the current model so the live plant uses:
%   - eCalc-derived RPM-to-thrust
%   - actuator-disk slipstream per prop
%   - four wing strip-type subsystems
%   - an elevator-driven tail subsystem

if nargin < 1 || isempty(modelName)
    modelName = 'blown_wing_model';
end

init_params;
assign_aliases_to_base(params, initial_pos_ned, initial_vel_body, initial_euler, initial_rates);

open_system(modelName);

update_propulsion_functions(modelName);
rebuild_aero_sectioned(modelName);
connect_top_level_controls(modelName);

save_system(modelName);
fprintf('Updated %s with sectioned blown-wing aero and tail control wiring.\n', modelName);
end

function assign_aliases_to_base(params, initial_pos_ned, initial_vel_body, initial_euler, initial_rates)
assignin('base', 'params', params);
assignin('base', 'initial_pos_ned', initial_pos_ned);
assignin('base', 'initial_vel_body', initial_vel_body);
assignin('base', 'initial_euler', initial_euler);
assignin('base', 'initial_rates', initial_rates);

fields = {
    'lt','D_prop','prop_rpm_grid','prop_thrust_grid','alpha_deg_grid', ...
    'cl_clean_baseline','cl_blow_only','cl_flap_only','cl_all_high_lift', ...
    'cd_clean_baseline','cd_blow_only','cd_flap_only','cd_all_high_lift', ...
    'cm_clean_baseline','cm_blow_only','cm_flap_only','cm_all_high_lift', ...
    'y_dist','b','c','cg_x_m','prop_axial_x_m','flap_span_fraction', ...
    'flap_deflection_slow','k_span_expansion','S_ht','c_ht','b_ht', ...
    'CL_alpha_ht','CL_delta_e'
    };
for i = 1:numel(fields)
    assignin('base', fields{i}, params.(fields{i}));
end
end

function update_propulsion_functions(modelName)
set_matlab_function_script(modelName, 'Propulsion_and_Slipstream/RPM_to_Thrust', rpm_to_thrust_script());
set_matlab_function_script(modelName, 'Propulsion_and_Slipstream/Slip_Stream', slipstream_script());

configure_chart_parameters(modelName, 'Propulsion_and_Slipstream/RPM_to_Thrust', ...
    {'prop_rpm_grid', 'prop_thrust_grid'});
configure_chart_parameters(modelName, 'Propulsion_and_Slipstream/Slip_Stream', ...
    {'D_prop'});
cleanup_chart_data(modelName, 'Propulsion_and_Slipstream/RPM_to_Thrust', ...
    {'RPMs', 'rho'}, {'Thrusts'}, {'prop_rpm_grid', 'prop_thrust_grid'});
cleanup_chart_data(modelName, 'Propulsion_and_Slipstream/Slip_Stream', ...
    {'Thrusts', 'Va', 'rho'}, {'V_slip'}, {'D_prop'});
end

function rebuild_aero_sectioned(modelName)
aeroPath = [modelName '/Aerodynamics_Strip_Theory'];

ensure_inport(aeroPath, 'Control_Cmds', 5, [35, 290, 65, 304]);
comment_legacy_aero_blocks(aeroPath);
disconnect_outport(aeroPath, 'Aero_Forces');
disconnect_outport(aeroPath, 'Aero_Moments');

ensure_block('simulink/Signal Routing/Demux', [aeroPath '/Control_Demux'], [110, 270, 145, 320]);
set_param([aeroPath '/Control_Demux'], 'Outputs', '2');

create_wing_section_subsystem(aeroPath, 'Wing_Clean_NoFlap', [250, 40, 470, 140], false, false);
create_wing_section_subsystem(aeroPath, 'Wing_Blown_NoFlap', [250, 165, 470, 265], true, false);
create_wing_section_subsystem(aeroPath, 'Wing_Clean_Flap', [250, 290, 470, 390], false, true);
create_wing_section_subsystem(aeroPath, 'Wing_Blown_Flap', [250, 415, 470, 515], true, true);
create_tail_subsystem(aeroPath, 'Tail_Aero', [250, 540, 470, 640]);

ensure_block('simulink/Math Operations/Sum', [aeroPath '/Wing_Force_Sum'], [575, 190, 595, 260]);
ensure_block('simulink/Math Operations/Sum', [aeroPath '/Wing_Moment_Sum'], [575, 355, 595, 425]);
ensure_block('simulink/Math Operations/Sum', [aeroPath '/Total_Force_Sum'], [760, 250, 780, 300]);
ensure_block('simulink/Math Operations/Sum', [aeroPath '/Total_Moment_Sum'], [760, 390, 780, 440]);
set_param([aeroPath '/Wing_Force_Sum'], 'Inputs', '++++');
set_param([aeroPath '/Wing_Moment_Sum'], 'Inputs', '++++');
set_param([aeroPath '/Total_Force_Sum'], 'Inputs', '++');
set_param([aeroPath '/Total_Moment_Sum'], 'Inputs', '++');

safe_add_line(aeroPath, 'Control_Cmds/1', 'Control_Demux/1');

wingNames = {'Wing_Clean_NoFlap', 'Wing_Blown_NoFlap', 'Wing_Clean_Flap', 'Wing_Blown_Flap'};
for i = 1:numel(wingNames)
    safe_add_line(aeroPath, 'V_b/1', [wingNames{i} '/1']);
    safe_add_line(aeroPath, 'rho1/1', [wingNames{i} '/2']);
    safe_add_line(aeroPath, 'V_slip/1', [wingNames{i} '/3']);
    safe_add_line(aeroPath, 'Control_Demux/2', [wingNames{i} '/4']);
    safe_add_line(aeroPath, [wingNames{i} '/1'], sprintf('Wing_Force_Sum/%d', i));
    safe_add_line(aeroPath, [wingNames{i} '/2'], sprintf('Wing_Moment_Sum/%d', i));
end

safe_add_line(aeroPath, 'V_b/1', 'Tail_Aero/1');
safe_add_line(aeroPath, 'Omega/1', 'Tail_Aero/2');
safe_add_line(aeroPath, 'rho1/1', 'Tail_Aero/3');
safe_add_line(aeroPath, 'Control_Demux/1', 'Tail_Aero/4');

safe_add_line(aeroPath, 'Wing_Force_Sum/1', 'Total_Force_Sum/1');
safe_add_line(aeroPath, 'Tail_Aero/1', 'Total_Force_Sum/2');
safe_add_line(aeroPath, 'Wing_Moment_Sum/1', 'Total_Moment_Sum/1');
safe_add_line(aeroPath, 'Tail_Aero/2', 'Total_Moment_Sum/2');
safe_add_line(aeroPath, 'Total_Force_Sum/1', 'Aero_Forces/1');
safe_add_line(aeroPath, 'Total_Moment_Sum/1', 'Aero_Moments/1');
end

function connect_top_level_controls(modelName)
safe_add_line(modelName, 'Demux/2', 'Aerodynamics_Strip_Theory/5');
end

function create_wing_section_subsystem(aeroPath, name, position, wantBlown, wantFlap)
subPath = [aeroPath '/' name];
recreate_subsystem(subPath, position);

add_block('simulink/Sources/In1', [subPath '/V_b'], 'Position', [30, 45, 60, 59]);
add_block('simulink/Sources/In1', [subPath '/rho'], 'Position', [30, 95, 60, 109], 'Port', '2');
add_block('simulink/Sources/In1', [subPath '/V_slip'], 'Position', [30, 145, 60, 159], 'Port', '3');
add_block('simulink/Sources/In1', [subPath '/delta_flap'], 'Position', [30, 195, 60, 209], 'Port', '4');
add_block('simulink/User-Defined Functions/MATLAB Function', [subPath '/Section_Aero'], ...
    'Position', [115, 50, 290, 210]);
add_block('simulink/Sinks/Out1', [subPath '/F_body'], 'Position', [345, 95, 375, 109]);
add_block('simulink/Sinks/Out1', [subPath '/M_body'], 'Position', [345, 155, 375, 169], 'Port', '2');

set_matlab_function_script_in_subsystem(subPath, 'Section_Aero', wing_section_script(wantBlown, wantFlap));
configure_chart_parameters_in_subsystem(subPath, 'Section_Aero', wing_parameter_names());
cleanup_chart_data_in_subsystem(subPath, 'Section_Aero', ...
    {'V_b', 'rho', 'V_slip', 'delta_flap'}, {'F_total', 'M_total'}, wing_parameter_names());

add_line(subPath, 'V_b/1', 'Section_Aero/1', 'autorouting', 'on');
add_line(subPath, 'rho/1', 'Section_Aero/2', 'autorouting', 'on');
add_line(subPath, 'V_slip/1', 'Section_Aero/3', 'autorouting', 'on');
add_line(subPath, 'delta_flap/1', 'Section_Aero/4', 'autorouting', 'on');
add_line(subPath, 'Section_Aero/1', 'F_body/1', 'autorouting', 'on');
add_line(subPath, 'Section_Aero/2', 'M_body/1', 'autorouting', 'on');
end

function create_tail_subsystem(aeroPath, name, position)
subPath = [aeroPath '/' name];
recreate_subsystem(subPath, position);

add_block('simulink/Sources/In1', [subPath '/V_b'], 'Position', [30, 45, 60, 59]);
add_block('simulink/Sources/In1', [subPath '/Omega'], 'Position', [30, 95, 60, 109], 'Port', '2');
add_block('simulink/Sources/In1', [subPath '/rho'], 'Position', [30, 145, 60, 159], 'Port', '3');
add_block('simulink/Sources/In1', [subPath '/delta_e'], 'Position', [30, 195, 60, 209], 'Port', '4');
add_block('simulink/User-Defined Functions/MATLAB Function', [subPath '/Tail_Aero'], ...
    'Position', [115, 50, 290, 210]);
add_block('simulink/Sinks/Out1', [subPath '/F_body'], 'Position', [345, 95, 375, 109]);
add_block('simulink/Sinks/Out1', [subPath '/M_body'], 'Position', [345, 155, 375, 169], 'Port', '2');

set_matlab_function_script_in_subsystem(subPath, 'Tail_Aero', tail_aero_script());
configure_chart_parameters_in_subsystem(subPath, 'Tail_Aero', ...
    {'lt', 'S_ht', 'c_ht', 'CL_alpha_ht', 'CL_delta_e'});
cleanup_chart_data_in_subsystem(subPath, 'Tail_Aero', ...
    {'V_b', 'Omega', 'rho', 'delta_e'}, {'F_total', 'M_total'}, ...
    {'lt', 'S_ht', 'c_ht', 'CL_alpha_ht', 'CL_delta_e'});

add_line(subPath, 'V_b/1', 'Tail_Aero/1', 'autorouting', 'on');
add_line(subPath, 'Omega/1', 'Tail_Aero/2', 'autorouting', 'on');
add_line(subPath, 'rho/1', 'Tail_Aero/3', 'autorouting', 'on');
add_line(subPath, 'delta_e/1', 'Tail_Aero/4', 'autorouting', 'on');
add_line(subPath, 'Tail_Aero/1', 'F_body/1', 'autorouting', 'on');
add_line(subPath, 'Tail_Aero/2', 'M_body/1', 'autorouting', 'on');
end

function recreate_subsystem(subPath, position)
if exist_block(subPath)
    delete_block(subPath);
end
add_block('simulink/Ports & Subsystems/Subsystem', subPath, 'Position', position);
innerBlocks = find_system(subPath, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(innerBlocks)
    delete_block(innerBlocks{i});
end
end

function tf = exist_block(path)
try
    get_param(path, 'Handle');
    tf = true;
catch
    tf = false;
end
end

function ensure_block(libPath, dstPath, position)
if ~exist_block(dstPath)
    add_block(libPath, dstPath, 'Position', position);
else
    set_param(dstPath, 'Position', position);
end
end

function ensure_inport(subsystemPath, name, portNumber, position)
path = [subsystemPath '/' name];
if ~exist_block(path)
    add_block('simulink/Sources/In1', path, 'Position', position, 'Port', num2str(portNumber));
else
    set_param(path, 'Port', num2str(portNumber), 'Position', position);
end
end

function comment_legacy_aero_blocks(aeroPath)
legacyBlocks = {
    '1X3_Zero','Atan2','CD','CL','CM','C_Y','C_l_Roll','C_n_Yaw','Coefficients', ...
    'Constant','Constant1','Constant2','Constant3','Constant4','Demux','Divide', ...
    'Dot Product','Gain','Gain1','Gain2','Lever_Arm_Constant','MATLAB Function1', ...
    'Pitch_gain','Product','Product1','Product2','Roll_Pitch_Yaw_moments', ...
    'Selector','Sqrt','Square','Square1','Sum','Sum of Elements','Sum2','Sum3', ...
    'Sum4','Sum5','Unblown_Aero','Horizontal_Tail_Model'
    };
for i = 1:numel(legacyBlocks)
    path = [aeroPath '/' legacyBlocks{i}];
    if exist_block(path)
        set_param(path, 'Commented', 'on');
    end
end
end

function disconnect_outport(aeroPath, outName)
ph = get_param([aeroPath '/' outName], 'PortHandles');
if isfield(ph, 'Inport') && ~isempty(ph.Inport)
    lineHandle = get_param(ph.Inport(1), 'Line');
    if isnumeric(lineHandle) && lineHandle ~= -1
        delete_line(lineHandle);
    end
end
end

function safe_add_line(systemPath, src, dst)
try
    add_line(systemPath, src, dst, 'autorouting', 'on');
catch ME
    if ~contains(ME.message, 'already exists') && ...
       ~contains(ME.message, 'The port is already connected') && ...
       ~contains(ME.message, 'destination port already has a line connection')
        rethrow(ME);
    end
end
end

function names = wing_parameter_names()
names = {
    'y_dist','D_prop','b','c','cg_x_m','prop_axial_x_m','flap_span_fraction', ...
    'flap_deflection_slow','k_span_expansion','alpha_deg_grid', ...
    'cl_clean_baseline','cl_blow_only','cl_flap_only','cl_all_high_lift', ...
    'cd_clean_baseline','cd_blow_only','cd_flap_only','cd_all_high_lift', ...
    'cm_clean_baseline','cm_blow_only','cm_flap_only','cm_all_high_lift'
    };
end

function set_matlab_function_script(modelName, blockPathSuffix, scriptText)
chartPath = [modelName '/' blockPathSuffix];
set_matlab_function_script_in_subsystem(fileparts(chartPath), erase(chartPath, [fileparts(chartPath) '/']), scriptText);
end

function set_matlab_function_script_in_subsystem(subPath, blockName, scriptText)
rt = sfroot;
chartPath = [subPath '/' blockName];
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', chartPath);
if isempty(chart)
    error('Could not find MATLAB Function block: %s', chartPath);
end
chart.Script = scriptText;
end

function configure_chart_parameters(modelName, blockPathSuffix, parameterNames)
chartPath = [modelName '/' blockPathSuffix];
configure_chart_parameters_in_subsystem(fileparts(chartPath), erase(chartPath, [fileparts(chartPath) '/']), parameterNames);
end

function configure_chart_parameters_in_subsystem(subPath, blockName, parameterNames)
rt = sfroot;
chartPath = [subPath '/' blockName];
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', chartPath);
if isempty(chart)
    error('Could not find MATLAB Function block: %s', chartPath);
end

allData = chart.find('-isa', 'Stateflow.Data');
for i = 1:numel(allData)
    if strcmp(allData(i).Scope, 'Parameter')
        delete(allData(i));
    end
end

for i = 1:numel(parameterNames)
    d = Stateflow.Data(chart);
    d.Name = parameterNames{i};
    d.Scope = 'Parameter';
end
end

function cleanup_chart_data(modelName, blockPathSuffix, inputNames, outputNames, parameterNames)
chartPath = [modelName '/' blockPathSuffix];
cleanup_chart_data_in_subsystem(fileparts(chartPath), erase(chartPath, [fileparts(chartPath) '/']), ...
    inputNames, outputNames, parameterNames);
end

function cleanup_chart_data_in_subsystem(subPath, blockName, inputNames, outputNames, parameterNames)
rt = sfroot;
chartPath = [subPath '/' blockName];
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', chartPath);
if isempty(chart)
    error('Could not find MATLAB Function block: %s', chartPath);
end

keep = [inputNames(:); outputNames(:); parameterNames(:)];
allData = chart.find('-isa', 'Stateflow.Data');
for i = 1:numel(allData)
    if ~any(strcmp(allData(i).Name, keep))
        delete(allData(i));
    end
end
end

function txt = rpm_to_thrust_script()
txt = sprintf([ ...
'function Thrusts = RPM_to_Thrust(RPMs, rho)\n' ...
'rpmGrid = prop_rpm_grid(:);\n' ...
'thrustGrid = prop_thrust_grid(:);\n' ...
'Thrusts = zeros(size(RPMs));\n' ...
'for i = 1:numel(RPMs)\n' ...
'    rpm = min(max(RPMs(i), rpmGrid(1)), rpmGrid(end));\n' ...
'    Thrusts(i) = max(interp1(rpmGrid, thrustGrid, rpm, ''linear''), 0);\n' ...
'end\n' ...
'end\n']);
end

function txt = slipstream_script()
txt = sprintf([ ...
'function V_slip = slipstream_calc(Thrusts, Va, rho)\n' ...
'A_prop = pi * (D_prop / 2)^2;\n' ...
'rho_safe = max(rho, 0.1);\n' ...
'T_safe = max(Thrusts, 0);\n' ...
'V_slip = sqrt(max(Va, 0)^2 + (2 .* T_safe) ./ max(rho_safe * A_prop, 1.0e-9));\n' ...
'end\n']);
end

function txt = wing_section_script(wantBlown, wantFlap)
txt = sprintf([ ...
'function [F_total, M_total] = Section_Aero(V_b, rho, V_slip, delta_flap)\n' ...
'wantBlown = %d;\n' ...
'wantFlap = %d;\n' ...
'F_total = zeros(3,1);\n' ...
'M_total = zeros(3,1);\n' ...
'Vb = reshape(V_b, 3, 1);\n' ...
'Vsl = V_slip(:);\n' ...
'u = Vb(1);\n' ...
'w = Vb(3);\n' ...
'Va = sqrt(sum(Vb.^2)) + 1.0e-3;\n' ...
'alpha = atan2(w, u);\n' ...
'alphaDeg = alpha * 180.0 / pi;\n' ...
'qInf = 0.5 * rho * Va^2;\n' ...
'posMask = y_dist(:) > 0;\n' ...
'posCenters = y_dist(posMask);\n' ...
'posSlip = Vsl(posMask);\n' ...
'blownHalfWidth = 0.5 * k_span_expansion * D_prop;\n' ...
'semiSpan = 0.5 * b;\n' ...
'flapEnd = flap_span_fraction * semiSpan;\n' ...
'edgeList = [0; flapEnd; semiSpan; max(posCenters - blownHalfWidth, 0); min(posCenters + blownHalfWidth, semiSpan)];\n' ...
'edgeList = sort(unique(edgeList));\n' ...
'flapMix = min(max(abs(delta_flap) / max(flap_deflection_slow, 1.0e-6), 0), 1);\n' ...
'ca = cos(alpha);\n' ...
'sa = sin(alpha);\n' ...
'Rsb = [ca, 0, -sa; 0, 1, 0; sa, 0, ca];\n' ...
'for i = 1:(numel(edgeList) - 1)\n' ...
'    y0 = edgeList(i);\n' ...
'    y1 = edgeList(i + 1);\n' ...
'    width = y1 - y0;\n' ...
'    if width <= 1.0e-6\n' ...
'        continue;\n' ...
'    end\n' ...
'    yMid = 0.5 * (y0 + y1);\n' ...
'    isFlapRegion = (yMid <= flapEnd + 1.0e-9);\n' ...
'    overlapMask = (posCenters + blownHalfWidth > y0) & (posCenters - blownHalfWidth < y1);\n' ...
'    isBlownRegion = any(overlapMask);\n' ...
'    if isFlapRegion ~= wantFlap || isBlownRegion ~= wantBlown\n' ...
'        continue;\n' ...
'    end\n' ...
'    qLocal = qInf;\n' ...
'    if isBlownRegion\n' ...
'        vLocal = mean(posSlip(overlapMask));\n' ...
'        qLocal = 0.5 * rho * vLocal^2;\n' ...
'    end\n' ...
'    if wantBlown\n' ...
'        clNoFlap = interp1(alpha_deg_grid, cl_blow_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cdNoFlap = interp1(alpha_deg_grid, cd_blow_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cmNoFlap = interp1(alpha_deg_grid, cm_blow_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'        clFlap = interp1(alpha_deg_grid, cl_all_high_lift, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cdFlap = interp1(alpha_deg_grid, cd_all_high_lift, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cmFlap = interp1(alpha_deg_grid, cm_all_high_lift, alphaDeg, ''linear'', ''extrap'');\n' ...
'    else\n' ...
'        clNoFlap = interp1(alpha_deg_grid, cl_clean_baseline, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cdNoFlap = interp1(alpha_deg_grid, cd_clean_baseline, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cmNoFlap = interp1(alpha_deg_grid, cm_clean_baseline, alphaDeg, ''linear'', ''extrap'');\n' ...
'        clFlap = interp1(alpha_deg_grid, cl_flap_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cdFlap = interp1(alpha_deg_grid, cd_flap_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'        cmFlap = interp1(alpha_deg_grid, cm_flap_only, alphaDeg, ''linear'', ''extrap'');\n' ...
'    end\n' ...
'    if wantFlap\n' ...
'        CL = clNoFlap + flapMix * (clFlap - clNoFlap);\n' ...
'        CD = cdNoFlap + flapMix * (cdFlap - cdNoFlap);\n' ...
'        Cm = cmNoFlap + flapMix * (cmFlap - cmNoFlap);\n' ...
'    else\n' ...
'        CL = clNoFlap;\n' ...
'        CD = cdNoFlap;\n' ...
'        Cm = cmNoFlap;\n' ...
'    end\n' ...
'    areaStrip = c * width;\n' ...
'    Fstab = qLocal * areaStrip * [-CD; 0; -CL];\n' ...
'    Fbody = Rsb * Fstab;\n' ...
'    Maero = qLocal * areaStrip * [0; Cm * c; 0];\n' ...
'    y = yMid;\n' ...
'    rVec = [prop_axial_x_m - cg_x_m; y; 0];\n' ...
'    Mlever = cross(rVec, Fbody);\n' ...
'    F_total = F_total + Fbody;\n' ...
'    M_total = M_total + Maero + Mlever;\n' ...
'    y = -yMid;\n' ...
'    rVec = [prop_axial_x_m - cg_x_m; y; 0];\n' ...
'    Mlever = cross(rVec, Fbody);\n' ...
'    F_total = F_total + Fbody;\n' ...
'    M_total = M_total + Maero + Mlever;\n' ...
'end\n' ...
'end\n'], wantBlown, wantFlap);
end

function txt = tail_aero_script()
txt = sprintf([ ...
'function [F_total, M_total] = Tail_Aero(V_b, Omega, rho, delta_e)\n' ...
'F_total = zeros(3,1);\n' ...
'M_total = zeros(3,1);\n' ...
'Vb = reshape(V_b, 3, 1);\n' ...
'Wb = reshape(Omega, 3, 1);\n' ...
'rTail = [-lt; 0; 0];\n' ...
'Vtail = Vb + cross(Wb, rTail);\n' ...
'u_t = Vtail(1);\n' ...
'w_t = Vtail(3);\n' ...
'Va_t = sqrt(sum(Vtail.^2)) + 0.1;\n' ...
'alpha_t = atan2(w_t, u_t);\n' ...
'qTail = 0.5 * rho * Va_t^2;\n' ...
'CL = CL_alpha_ht * alpha_t + CL_delta_e * delta_e;\n' ...
'CD = 0.02 + 0.06 * CL^2;\n' ...
'Cm = -0.15 * delta_e;\n' ...
'ca = cos(alpha_t);\n' ...
'sa = sin(alpha_t);\n' ...
'Rsb = [ca, 0, -sa; 0, 1, 0; sa, 0, ca];\n' ...
'Fstab = qTail * S_ht * [-CD; 0; -CL];\n' ...
'Fbody = Rsb * Fstab;\n' ...
'Mbody = qTail * S_ht * [0; Cm * c_ht; 0] + cross(rTail, Fbody);\n' ...
'F_total = Fbody;\n' ...
'M_total = Mbody;\n' ...
'end\n']);
end
